name: Salesforce Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@2.139.6

      # Verify Installation
      - name: Verify CLI
        run: |
          echo "Salesforce CLI Version"
          sf version

          echo "Node Version"
          node -v

          echo "NPM Version"
          npm -v

          echo "CLI Location"
          which sf

          echo "Installed Plugins"
          sf plugins

      # Create Auth File
      - name: Create Auth File
        run: |
          printf '%s' "${{ secrets.SFDX_AUTH_URL }}" > auth.txt

      # Inspect Auth File
      - name: Inspect Auth File
        run: |
          echo "File Size:"
          wc -c auth.txt

          echo "Starts With:"
          head -c 20 auth.txt

          echo
          echo "Ends With:"
          tail -c 50 auth.txt

      # Verify Login Command Exists
      - name: Verify Login Command
        run: |
          sf org login sfdx-url --help

      # Authenticate
      - name: Authenticate to Salesforce Sandbox
        run: |
          sf org login sfdx-url \
            --sfdx-url-file auth.txt

      # Verify Authentication
      - name: Verify Org Connection
        run: |
          sf org list

      # Deploy
      - name: Deploy to Salesforce Sandbox
        run: |
          sf project deploy start \
            --target-org devsandbox \
            --source-dir force-app \
            --wait 30

      # Cleanup
      - name: Cleanup
        if: always()
        run: |
          rm -f auth.txt
