name: Salesforce Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      # Checkout Repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install Salesforce CLI
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli@2.139.6

          echo "Salesforce CLI Version"
          sf version

          echo "Node Version"
          node -v

          echo "NPM Version"
          npm -v

      # Verify CLI Installation
      - name: Verify CLI
        run: |
          which sf
          sf version
          sf plugins

      # Create Authentication File
      - name: Create Auth File
        run: |
          printf '%s' "${{ secrets.SFDX_AUTH_URL }}" > auth.txt

          echo "Auth file created successfully"

          ls -l auth.txt
          wc -c auth.txt

      # Authenticate to Salesforce Sandbox
      - name: Authenticate to Salesforce Sandbox
        run: |
          sf org login sfdx-url \
            --sfdx-url-file auth.txt \
            --alias devsandbox \
            --json

      # Verify Authentication
      - name: Verify Org Connection
        run: |
          sf org list

      # Deploy Metadata
      - name: Deploy to Salesforce Sandbox
        run: |
          sf project deploy start \
            --target-org devsandbox \
            --source-dir force-app \
            --wait 30

      # Cleanup
      - name: Cleanup
        if: always()
        run: |
          rm -f auth.txt
